apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: db-wp
  name: db-wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-wp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db-wp
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources: {}
        env: 
        - name: MYSQL_DATABASE
          value: exampledb
        - name: MYSQL_USER
          value: exampleuser
        - name: MYSQL_PASSWORD
          value: examplepass 
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: '1'
status: {}
