apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: db-wp
  name: db-wp
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db-wp
status:
  loadBalancer: {}
